title: Steven Watson Buehler
author: Steven Watson Buehler
email: alive.awakened@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  Late-40-something (going on 12). Data, chart, and theme park addict. Ravenclaw. My patronus is a St. Bernard.
show_excerpts: true # set to true to show excerpts on the homepage
baseurl:

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Steven Buehler
  tagline: Late-40-something (going on 12). Data, chart, and theme park addict. Ravenclaw. My patronus is a St. Bernard.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false
  navigation:
    link:
      title: "Colophon"
      url: "https://stevenbuehler.github.io/colophon"

  # generate social links in footer
  social_links:
    twitter: alive_awakened
    github: alive_awakened
    linkedIn: in/stevenwatsonb
    rss: rss
    twitch: alive_awakened
    instagram: alive_awakened
    facebook: stevenwbuehler

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - colophon.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed
