title: Steven Watson Buehler
author: Steven Watson Buehler
email: stevenwbuehler@icloud.com
description: > # this means to ignore newlines until "show_excerpts:"
  Late-40-something (going on 12). Data, chart, Harry Potter™, and theme park addict.
show_excerpts: false # set to true to show excerpts on the homepage
baseurl:

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

site:
  url: https://swbuehler.com

permalink: /posts/:title/
texture:
  title: Steven Buehler
  tagline: Late-40-something (going on 12). Data, chart, Harry Potter™, and theme park addict.
  date_format: "%m/%d/%Y"
  style: blue
  showNav: true
  showPicker: false
  navigation:
    - title: "Home"
      url: "/"
    - title: "About"
      url: "/about"
    - title: "Colophon"
      url: "/colophon"
    - title: "Personal Informatics"
      url: "/dataprojects"
    - title: "Contact"
      url: "/contact"
    - title: "Feed"
      url: "/feed.xml"
  disqus_shortname: steven-w-buehler
  # generate social links in footer
  social_links:
    twitter: gloriousabsence
    github: stevenbuehler
    linkedIn: in/stevenwatsonb
    rss: /feed.xml
    twitch: gloriousabsenceofskill
    instagram: gloriousabsenceofskill
    facebook: stevenwatsonbuehler
    tiktok: gloriousabsenceofskill
    snapchat: gloriousabsence

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - colophon.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-redirect-from

